import { VerticalBox } from "std-widgets.slint";
import { AuthLayout } from "../components/auth/auth_layout.slint";
import { IconLineEdit } from "../components/auth/icon_line_edit.slint";
import { ActionButton } from "../components/auth/action_button.slint";
import { StatusBox } from "../components/auth/status_box.slint";
import { AppTheme, AppStyles } from "../theme/colors.slint";

export component ChangePasswordWindow inherits AuthLayout {
    title: "Nouveau Mot de Passe";
    in-out property<string> new_password_text: "";
    in-out property<string> confirm_password_text: "";
    in-out property<string> status_text: "";
    in-out property<bool> loading: false;
    in-out property<bool> is_error: false;
    callback confirm_clicked(string);

    //card-width: 400px;
    //card-height: 540px;
    
    VerticalBox {
        padding: 30px;
        spacing: 20px;
        alignment: center;

        Rectangle { // Icône
            width: 80px; 
            height: 80px; 
            border-radius: 40px;
            background: AppTheme.accent-brush;
            Text { 
                text: "🔒"; 
                font-size: 32px; 
                vertical-alignment: center; 
                horizontal-alignment: center; 
            }
        }
        
        Text { 
            text: "Changement de mot de passe"; 
            font-size: 20px; 
            font-weight: 600; 
            color: AppStyles.text-title; 
        }
        
        Text { 
            text: "Définissez un nouveau mot de passe sécurisé"; 
            font-size: 13px; 
            color: AppStyles.text-body; 
        }

        VerticalBox {
            spacing: 15px;
            IconLineEdit { 
                icon: "🆕"; 
                placeholder_text: "Nouveau mot de passe"; 
                is_password: true; 
                text <=> root.new_password_text; 
            }
            IconLineEdit { 
                icon: "✅"; 
                placeholder_text: "Confirmer le mot de passe"; 
                is_password: true; 
                text <=> root.confirm_password_text; 
            }
        }
        
        ActionButton {
            text: "Confirmer";
            loading: root.loading;
            enabled: !root.loading && root.new_password_text != "" && root.new_password_text == root.confirm_password_text;
            clicked => { root.confirm_clicked(root.new_password_text) }
        }

        StatusBox { 
            text: root.status_text; 
            is_error: root.is_error; 
        }
    }
}