import { HorizontalBox, LineEdit } from "std-widgets.slint";
import { AppTheme, AppStyles } from "../../theme/colors.slint";

export component IconLineEdit inherits Rectangle {
    in-out property <string> text;
    in property <string> placeholder_text;
    in property <string> icon;
    in property <bool> is_password: false;

    height: 50px;
    background: AppTheme.background-overlay-dark;
    border-radius: AppStyles.border-radius;
    
    HorizontalBox {
        padding-left: 15px;
        padding-right: 15px;
        spacing: 12px;

        Text { 
            text: root.icon; 
            font-size: 16px; 
            color: AppTheme.text-muted; 
        }
        
        LineEdit {
            placeholder-text: root.placeholder_text;
            input-type: root.is_password ? InputType.password : InputType.text;
            text <=> root.text;
            font-size: 14px;
            horizontal-stretch: 1;
        }
    }
}