import { AppTheme, AppStyles } from "../../theme/colors.slint";

export component StatusBox inherits Rectangle {
    in property <string> text;
    in property <bool> is_error: false;

    height: 50px;
    
    // Visibilité
    visible: root.text != "";
    
    // Style
    background: root.is_error ? 
                AppTheme.with-alpha(AppTheme.state-error, 0.2) : 
                AppTheme.with-alpha(AppTheme.state-success, 0.2);
    border-radius: 8px;
    border-width: 1px;
    border-color: root.is_error ? 
                  AppTheme.with-alpha(AppTheme.state-error, 0.5) : 
                  AppTheme.with-alpha(AppTheme.state-success, 0.5);

    Text {
        text: root.text;
        horizontal-alignment: center;
        vertical-alignment: center;
        font-size: 13px;
        font-weight: 500;
        color: root.is_error ? 
               AppTheme.state-error : 
               AppTheme.state-success;
    }
}