// D'abord, on importe les composants des autres fichiers
import { LoginWindow } from "login.slint";
import { ChangePasswordWindow } from "change_password.slint";
import { MainWindow } from "main_window.slint";
import {AddUserWindow} from "add_user.slint";
import { ChangePasswordUserWindow } from "change_password_user.slint";


// Ensuite, on les ré-exporte pour que Rust puisse les voir
export { LoginWindow, ChangePasswordWindow, AddUserWindow, ChangePasswordUserWindow, MainWindow }