// src/ui/all_in_one.slint

// Importer les fenêtres principales et les dialogues
import { MainWindow } from "main.slint";
import { LoginWindow } from "./auth_views/login.slint";
import { ChangePasswordWindow } from "./auth_views/change_password.slint";
import { ChangePasswordUserWindow } from "./auth_views/change_password_user.slint"; 

// Importer les nouveaux dialogues de produits
import { AddProductDialog } from "./dialogs/add_product_dialog.slint";
import { EditProductDialog } from "./dialogs/edit_product_dialog.slint";
import { DeleteProductDialog } from "./dialogs/delete_product_dialog.slint";
import { AddUserDialog } from "./dialogs/add_user_dialog.slint";
import { EditUserDialog } from "./dialogs/edit_user_dialog.slint";
import { DeleteUserDialog } from "./dialogs/delete_user_dialog.slint";
import { ErrorDialog } from "./dialogs/error_dialog.slint";
import { InfoDialog } from "./dialogs/info_dialog.slint";
import { ConfirmDialog } from "./dialogs/confirm_dialog.slint";
import { NewSaleDialog } from "./dialogs/new_sale_dialog.slint";
import { ReceiptDialog } from "./dialogs/receipt_dialog.slint";
import { SaleDetailsDialog } from "./dialogs/sale_details_dialog.slint";

// Ré-exporter TOUT ce que Rust a besoin de `::new()`
export { 
    LoginWindow, 
    ChangePasswordWindow, 
    MainWindow, 
    ChangePasswordUserWindow,

    // Exporter les nouveaux dialogues
    AddProductDialog,
    EditProductDialog,
    DeleteProductDialog,
    AddUserDialog,
    EditUserDialog,
    DeleteUserDialog,
    ErrorDialog,
    InfoDialog,
    ConfirmDialog, 
    NewSaleDialog,
    ReceiptDialog,
    SaleDetailsDialog
}