// src/ui/change_password_user.slint

import { VerticalBox, LineEdit, Button } from "std-widgets.slint";

export component ChangePasswordUserWindow inherits Window {
    title: "Changer mon mot de passe";
    width: 400px;
    height: 350px;

    // Propriétés
    in-out property<string> old_password_text: "";
    in-out property<string> new_password_text: "";
    in-out property<string> confirm_password_text: "";
    in-out property<string> status_text: "";

    // Callbacks
    callback save_clicked(string, string); // old_password, new_password
    
    VerticalBox {
        padding: 20px;
        spacing: 10px;
        
        LineEdit { placeholder-text: "Ancien mot de passe"; input-type: InputType.password; text <=> root.old_password_text; }
        LineEdit { placeholder-text: "Nouveau mot de passe"; input-type: InputType.password; text <=> root.new_password_text; }
        LineEdit { placeholder-text: "Confirmer le mot de passe"; input-type: InputType.password; text <=> root.confirm_password_text; }

        Button {
            text: "Enregistrer";
            enabled: root.old_password_text != "" && root.new_password_text != "" && root.new_password_text == root.confirm_password_text;
            clicked => { root.save_clicked(root.old_password_text, root.new_password_text) }
        }
        Text { text: root.status_text; color: red; }
    }
}