// src/ui/components/menu_item.slint

import { HorizontalBox } from "std-widgets.slint";
import { AppTheme, AppStyles } from "../theme/colors.slint";

export component MenuItem inherits Rectangle {
    in property <string> text;
    in property <color> text_color: AppTheme.text-primary;
    callback clicked;

    height: 40px;
    
    // Fond transparent par défaut avec effet hover
    background: area.has-hover ? 
        AppTheme.background-overlay-light : 
        transparent;
    animate background { 
        duration: 200ms; 
        easing: AppStyles.animation-ease; 
    }

    area := TouchArea {
        mouse-cursor: pointer;
        clicked => { root.clicked() }
    }
    
    HorizontalBox {
        padding-left: 12px;
        spacing: 8px;
        
        Text {
            text: root.text;
            font-size: 13px;
            color: root.text_color;
        }
    }
}